{:user {:plugins [;[lein-pprint "1.1.1"]
                  ;[refactor-nrepl "2.3.1"]
                  [lein-try "0.4.3"]
                  [lein-cloverage "1.0.9"]
                  ;[jonase/eastwood "0.2.3"]
                  ]
        :dependencies [;[slamhound "1.5.5"]
 ;                      [spyscope "0.1.5" :exclusions [clj-time]]
;                       [org.clojure/tools.nrepl "0.2.12"] 
                       [debugger "0.2.1"]
                       [compliment "0.4.0-SNAPSHOT"]
;	               [cider/cider-nrepl "0.13.0"]
                       ;[proto-repl "0.3.1"]
;                       [cloverage "1.0.9"]
;                       [cljs-tooling "0.3.0"]
                       ;[com.billpiel/sayid "0.0.10"]
                       [org.clojure/tools.namespace "0.2.11"] 
                       ;[pjstadig/humane-test-output "0.8.1"]
                       ]
}}
